---
version: '3'
services:
  proxy:
    build:
      context: nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ./static/:/var/www/sparedomain.name/public/
      - ./keys/:/etc/letsencrypt/live/sparedomain.name/
    ports:
      - 4430:443
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    env_file: env_file
